const userTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SING_IN_ERROR: 'SIGN_IN_ERROR',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    RESET_EMAIL_SUCCESS: 'SIGN_UP_EMAIL_SUCCESS',
    RESET_EMAIL_ERROR: 'SIGN_UP_EMAIL_ERROR',
    SIGN_IN_WITH_GOOGLE_SUCCESS: 'SIGN_IN_WITH_GOOGLE_SUCCESS',
    SIGN_IN_WITH_GOOGLE_ERROR: 'SIGN_IN_WITH_GOOGLE_ERROR'
};

export default userTypes;